version: '3.8'

services:


  backend:
    build:
      context: ./backend
    container_name: scraper_backend
    restart: always
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      DATABASE_URL: sqlite+aiosqlite:///scraper.db
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      TENANT_ID: ${TENANT_ID}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SHAREPOINT_SITE_URL: ${SHAREPOINT_SITE_URL}
      SHAREPOINT_SITE_ID: ${SHAREPOINT_SITE_ID}
      TERM_SET_AREA_ID: ${TERM_SET_AREA_ID}
      TERM_SET_EMPRESA_ID: ${TERM_SET_EMPRESA_ID}
  frontend:
    build:
      context: ./frontend
    container_name: scraper_frontend
    restart: always
    ports:
      - "8501:8501"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend


